In [1]:
%autosave 0

Autosave disabled


# Dataset

In [2]:
import numpy as np

###### USE THIS DATA ########
# define a matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(A)
###### USE THIS DATA ########

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Create PCA and fit data

In [3]:
# import PCA from sklearn
from sklearn.decomposition import PCA as PCA_sklearn

# import PCA from module
from pca_mod import PCA as PCA_module

In [4]:
# create PCA instabce

pca_sklearn = PCA_sklearn(2)
pca_module = PCA_module(2)

In [5]:
# fit on data
# fit function

pca_sklearn.fit(A)
pca_module.fit(A)

# Compare attributes from module and sklearn

In [6]:
# access mean

print('PCA sklearn mean : ', pca_sklearn.mean_)
print('PCA module mean : ', pca_module.mean_)

PCA sklearn mean :  [5.5 6.5 7.5]
PCA module mean :  [5.5 6.5 7.5]


In [10]:
# access covariance

print('PCA sklearn covariance : ')
print(pca_sklearn.get_covariance())
print('\n')
print('PCA module covariance : ')
print(pca_module.covariance_)

PCA sklearn covariance : 
[[15. 15. 15.]
 [15. 15. 15.]
 [15. 15. 15.]]


PCA module covariance : 
[[15. 15. 15.]
 [15. 15. 15.]
 [15. 15. 15.]]


In [11]:
# access eigenvalues

print('PCA sklearn eigen values : ')
print(pca_sklearn.explained_variance_)
print('\n')
print('PCA module eigen values : ')
print(pca_module.explained_variance_)

PCA sklearn eigen values : 
[45.  0.]


PCA module eigen values : 
[45.  0.]


In [13]:
# access eigenvalues ratio

print('PCA sklearn eigen values ratio : ')
print(pca_sklearn.explained_variance_ratio_)
print('\n')
print('PCA module eigen values ratio : ')
print(pca_module.explained_variance_ratio_)

PCA sklearn eigen values ratio : 
[1. 0.]


PCA module eigen values ratio : 
[1. 0.]


In [14]:
# access eigenvectors

print('PCA sklearn eigen vectors : ')
print(pca_sklearn.components_)
print('\n')
print('PCA module eigen vectors : ')
print(pca_module.components_)

PCA sklearn eigen vectors : 
[[ 0.57735027  0.57735027  0.57735027]
 [ 0.         -0.70710678  0.70710678]]


PCA module eigen vectors : 
[[ 0.57735027  0.57735027  0.57735027]
 [ 0.         -0.70710678  0.70710678]]


# Compare methods from module and sklearn

In [16]:
# fit function already applied above
# transform function

A_sk = pca_sklearn.transform(A)
A_md = pca_module.transform(A)

print('PCA sklearn transform function output : ')
print(A_sk)
print('\n')
print('PCA module transform function output : ')
print(A_md)

PCA sklearn transform function output : 
[[-7.79422863e+00 -1.77635684e-15]
 [-2.59807621e+00 -4.44089210e-16]
 [ 2.59807621e+00  4.44089210e-16]
 [ 7.79422863e+00  1.77635684e-15]]


PCA module transform function output : 
[[-7.79422863e+00 -4.44089210e-16]
 [-2.59807621e+00 -2.22044605e-16]
 [ 2.59807621e+00  2.22044605e-16]
 [ 7.79422863e+00  4.44089210e-16]]


In [17]:
# reverse transform function
# revert from transformed matrix to original matrix

B_sk = pca_sklearn.inverse_transform(A_sk)
B_md = pca_module.inverse_transform(A_md)

print('PCA sklearn inverse transform function output : ')
print(B_sk)
print('\n')
print('PCA module inverse transform function output : ')
print(B_md)

PCA sklearn inverse transform function output : 
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


PCA module inverse transform function output : 
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
